# PQS v3 配置
thresholds:
  publish_score: 85
  keyword_density_max: 0.025
  min_inline_images: 2
entities_tokens:
  generic: ["matter","thread","zigbee","local control","watt","2.4g","hub"]
  smart-plugs: ["smart plug","energy","monitor","kwh","standby"]
  smart-cameras: ["rtsp","onvif","privacy shutter","fps"]
weights:
  depth: 30
  evidence: 20
  images: 15
  structure: 15
  readability: 10
  compliance: 10
